---
title: "Curriculum Vitae"
format:
  html:
    toc: true
---

::: {.d-block .d-sm-flex .align-items-center}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">

<a class="btn btn-primary btn-lg" href="resume.pdf" download role="button"> <i class="fas fa-download"></i> Download CV</a>
:::

## Education

-   Doctor of Philosophy, Monash University, Jan 2023 - present

-   Doctor of Philosophy, University of Melbourne, June 2022 - Jan 2023

-   Bachelor of Commerce with Honors, Monash University, 2017-2020

## Research Projects

-   **Learning Financial Jumps with Infinite Gaussian Mixture** (with [Ole Maneesoonthorn](https://sites.google.com/view/o-maneesoonthorn/home), [Yong Song](https://sites.google.com/view/ysong1), [Wei Wei](https://sites.google.com/site/wwei0936))

-   [**Optimal probabilistic forecasts for risk management**](https://arxiv.org/abs/2303.01651) (with [Ole Maneesoonthorn](https://sites.google.com/view/o-maneesoonthorn/home), [Ruben Loaiza-Maya](https://sites.google.com/view/rubenloaizamaya), [Gael Martin](https://scholar.google.com/citations?user=Uq0_yNgAAAAJ&hl=en))

## Talks

-   Econometrics Society World Congress (2025)

-   The European Seminar on Bayesian Econometrics (2025)

-   The 8th International Conference on Econometrics and Statistics (2025)

-   International Association for Applied Econometrics (2025)

-   Econometric Society Australasian Meeting (2024)

-   Time Series and Forecasting Symposium (2024)

## Work Experience

-   **Teaching Associate**, Monash Business School, Feb 2023 - present

    -   High Dimensional Data Analysis (Head tutor)

    -   Data Analysis in Business (Excellent teaching team)

    -   Introductory Econometrics

    -   Business Statistics

    -   Business Forecasting

        (*Teaching evaluation reports available upon request*)

-   **Research Assistant**, Monash Business School, Aug 2023 - Oct 2024

    -   High frequency data analysis of bond data for the Thailand Bond Market Association. Evaluate bond price jumps under the influence of regulation changes.

-   **Research Assistant**, Monash Business School, Aug 2022 - Dec 2022

    -   Data cleaning of high-frequency stock data

## Honors & Awards

-   **Prestigious International Conference Award**, Monash University, 2025

-   **CFM/SoFiE Scholarship**, Capital Fund Management, The Society for Financial Econometrics, 2025

-   **Best Poster Runner Up**, Time Series and Forecasting Symposium, Univeristy of Sydney, 2024

-   **Co-funded Monash Graduate Scholarship**, Monash University, 2023

-   **Monash Business School Top-up Scholarship**, Monash Business School, 2023

-   **Faculty of Business and Economics Graduate Research Scholarship**, University of Melbourne, 2022

-   **Dean's Honor (First Class)**, Monash University, 2021,

-   **Econometrics Memorial Scholarship**, Monash Business School, 2020

-   **Meritorious Winner**, Interdisciplinary Contest in Modeling, 2020
